topic_camera: "/dope/webcam/image_raw"
topic_camera_info: "/dope/webcam/camera_info"
topic_publishing: "dope"
input_is_rectified: True   # Whether the input image is rectified (strongly suggested!)
downscale_height: 400      # if the input image is larger than this, scale it down to this pixel height

# Comment any of these lines to prevent detection / pose estimation of that object
weights: {
    # "cracker":"package://dope/weights/cracker_60.pth",
    # "gelatin":"package://dope/weights/gelatin_60.pth",
    # "meat":"package://dope/weights/meat_20.pth",
    # "mustard":"package://dope/weights/mustard_60.pth",
    # "soup":"package://dope/weights/soup_60.pth",
    # 'peg_hole': "package://dope/weights/peg_box_40.pth",
    # 'cube_red': "package://dope/weights/red_40.pth",
    # "sugar":"package://dope/weights/sugar_60.pth"
    # "bleach":"package://dope/weights/bleach_28_dr.pth"
    # 'pudding':"weights_dope/pudding.pth"
    # 'pudding':"weights_dope/dope_network/net_epoch_60.pth"
    # 'alphabet_soup':"weights_dope/resnet_simple/alphabe_soup.pth"
    # "Ketchup":"D:/Desktop/1/individual_project/Deep_Object_Pose_Windows/scripts/train2/weights_dope/Ketchup.pth",
    # "cracker":"weights_dope/cracker_60.pth",
    # "gelatin":"weights_dope/gelatin_60.pth",
    # "meat":"weights_dope/meat_20.pth",
    # "mustard":"weights_dope/mustard_60.pth",
    # "soup":"weights_dope/soup_60.pth",
    # 'peg_hole': "weights_dope/peg_box_40.pth",
    # "sugar":"weights_dope/sugar_60.pth",
    # "bleach":"weights_dope/bleach_28_dr.pth",
    # 'alphabet_soup':"weights_dope/resnet_simple/alphabe_soup.pth",
    "macaroni_and_cheese":"D:/Desktop/1/individual_project/Deep_Object_Pose_Windows/scripts/train2/weights_dope/MacaroniAndCheese.pth",
    # "butter":"train2/weights_dope/Butter.pth"
}

# Type of neural network architecture
architectures: {
    # 'pudding':"dope",
    # 'alphabet_soup':'dope',
    # 'Ketchup':'dope',
    # 'alphabet_soup':'resnet_simple',  
    'macaroni_and_cheese':"dope",
    # 'butter':"dope",
}


# Cuboid dimension in cm x,y,z
dimensions: {
    # "cracker": [16.403600692749023,21.343700408935547,7.179999828338623],
    # "gelatin": [8.918299674987793, 7.311500072479248, 2.9983000755310059],
    # "meat": [10.164673805236816,8.3542995452880859,5.7600898742675781],
    # "mustard": [9.6024150848388672,19.130100250244141,5.824894905090332],
    # "soup": [6.7659378051757813,10.185500144958496,6.771425724029541],
    # "sugar": [9.267730712890625,17.625339508056641,4.5134143829345703],
    # "bleach": [10.267730712890625,26.625339508056641,7.5134143829345703],
    # "peg_hole": [12.6,3.9,12.6],
    # 'cube_red':[5,5,5],
    # 'pudding':[49.47199821472168, 29.923000335693359, 83.498001098632812],
    # 'alphabet_soup':[8.3555002212524414, 7.1121001243591309, 6.6055998802185059],
    # "Ketchup" : [ 14.860799789428711, 4.3368000984191895, 6.4513998031616211 ],
    "macaroni_and_cheese":[ 16.625600814819336, 4.0180997848510742, 12.350899696350098 ],
    # "butter":[81.776772, 64.240250, 60.322884], 
}

class_ids: {
    "cracker": 1,
    "gelatin": 2,
    "meat":    3,
    "mustard": 4,
    "soup":    5,
    "sugar":   6,
    "bleach":  7,
    "peg_hole": 8,
    "cube_red": 9,
    'pudding': 10,
    'alphabet_soup': 12,
    "Ketchup": 13,
    "macaroni_and_cheese": 14,
    "butter":15,
}

draw_colors: {
    "cracker": [13, 255, 128],  # green
    "gelatin": [255, 255, 255],  # while
    "meat": [0, 104, 255],  # blue
    "mustard": [217,12, 232],  # magenta
    "soup": [255, 101, 0],  # orange
    "sugar": [232, 222, 12],  # yellow
    "bleach": [232, 222, 12],  # yellow
    "peg_hole": [232, 222, 12],  # yellow
    "cube_red": [255,0,0],
    "pudding": [255,0,0],
    "macaroni_and_cheese": [255,0,0],
    "butter": [0,255,255],
    'Ketchup': [232, 222, 12], # yellow
}

# optional: provide a transform that is applied to the pose returned by DOPE
model_transforms: {
    # "cracker": [[ 0,  0,  1,  0],
    #             [ 0, -1,  0,  0],
    #             [ 1,  0,  0,  0],
    #             [ 0,  0,  0,  1]]
    "macaroni_and_cheese": [[ 0,  -1,  0,  0],
                [ 0, 0,  -1,  0],
                [ 1,  0,  0,  0],
                [ 0,  0,  0,  1]]
    # "Ketchup": [[ 0,  0,  1,  0],
    #                          [ 0, -1,  0,  0],
    #                          [ 1,  0,  0,  0],
    #                          [ 0,  0,  0,  1]]
}

# optional: if you provide a mesh of the object here, a mesh marker will be
# published for visualization in RViz
# You can use the nvdu_ycb tool to download the meshes: https://github.com/NVIDIA/Dataset_Utilities#nvdu_ycb
meshes: {
#    "cracker": "file://path/to/Dataset_Utilities/nvdu/data/ycb/aligned_cm/003_cracker_box/google_16k/textured.obj",
#    "gelatin": "file://path/to/Dataset_Utilities/nvdu/data/ycb/aligned_cm/009_gelatin_box/google_16k/textured.obj",
#    "meat":    "file://path/to/Dataset_Utilities/nvdu/data/ycb/aligned_cm/010_potted_meat_can/google_16k/textured.obj",
#    "mustard": "file://path/to/Dataset_Utilities/nvdu/data/ycb/aligned_cm/006_mustard_bottle/google_16k/textured.obj",
#    "soup":    "file://path/to/Dataset_Utilities/nvdu/data/ycb/aligned_cm/005_tomato_soup_can/google_16k/textured.obj",
#    "sugar":   "file://path/to/Dataset_Utilities/nvdu/data/ycb/aligned_cm/004_sugar_box/google_16k/textured.obj",
#    "bleach":  "file://path/to/Dataset_Utilities/nvdu/data/ycb/aligned_cm/021_bleach_cleanser/google_16k/textured.obj",
     "macaroni_and_cheese": "file:://D:Desktop/1/individual_project/dope/scripts/nvisii_data_gen/models/MacaroniAndCheese/google_16k/textured.obj",
     "butter": "file:://D:Desktop/1/individual_project/dope/scripts/nvisii_data_gen/models/Butter/google_16k/textured.obj",
}

# optional: If the specified meshes are not in meters, provide a scale here (e.g. if the mesh is in centimeters, scale should be 0.01). default scale: 1.0.
mesh_scales: {
    "cracker": 0.01,
    "gelatin": 0.01,
    "meat":    0.01,
    "mustard": 0.01,
    "soup":    0.01,
    "sugar":   0.01,
    "bleach":  0.01,
    "macaroni_and_cheese": 0.01, # my code
    "butter": 0.01,
    'Ketchup': 0.01,
}

# Config params for DOPE
thresh_angle: 0.5
thresh_map: 0.0001
sigma: 3
thresh_points: 0.1
